server:
  port: 8088

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: booking-service-route
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**

        - id: category-service-route
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/categories/**

        - id: payment-service-route
          uri: lb://PAYMENT
          predicates:
            - Path=/api/payments/**

        - id: salon-service-route
          uri: lb://SALON-SERVICE
          predicates:
            - Path=/salons/**,/api/salons/**,/api/admin/salons/**

        - id: service-offering-route
          uri: lb://SERVICE-OFFERING
          predicates:
            - Path=/api/service-offering/**

        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**,/api/admin/users/**,/api/users/**

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"