server:
  port: 5007

spring:
  application:
    name: notification

  cloud:
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/notification-db
    username: postgres
    password: Saumya@70
    driver-class-name: org.postgresql.Driver


  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8070/eureka/
