spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/salon-db
spring.datasource.username=postgres
spring.datasource.password=Saumya@70

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port = 8081
